#!/usr/bin/env python3
"""
OpenSEO-Lite CLI
Usage:
    python cli.py site_audit --url="https://example.com"
    python cli.py site_audit --url="https://example.com" --export=json
    python cli.py site_audit --url="https://example.com" --export=md
    python cli.py serp_search --keyword="ai agents" --location="us" --export=json
    python cli.py page_audit --url="https://example.com" --export=json
    python cli.py ai_visibility_check --brand="Acme" --domain="acme.com"
    python cli.py ai_visibility_check --brand="Acme" --domain="acme.com" --live --export=md
"""

import argparse
import asyncio
import json
import sys
from typing import Dict, Any

from skills.serp_search import serp_search
from skills.page_audit import page_audit
from skills.site_audit import site_audit
from skills.ai_visibility_check import ai_visibility_check


def export_json(data: Dict[str, Any], filepath: str) -> None:
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"✓ JSON report saved to: {filepath}")


def export_markdown_report(data: Dict[str, Any], filepath: str) -> None:
    """Generate and write a clean Markdown SEO report."""
    md = f"""# OpenSEO-Lite Audit Report
**Target URL:** {data.get('url', 'N/A')}  
**SEO Health Score:** {data.get('seo_score', 0)}/100  
**Generated by:** OpenSEO-Lite Agent (Naga Codex)  

---

## Executive AI Summary & Strategic Advice
{data.get('ai_summary', 'No summary available.')}

---

## Estimated CWV (heuristic — not live CrUX)
| Metric | Value | Rating | Target |
|---|---|---|---|
| **LCP** | {data.get('crux', {}).get('lcp', 'N/A')} | {data.get('crux', {}).get('lcp_rating', 'N/A').upper()} | < 2.5s |
| **FID / INP** | {data.get('crux', {}).get('fid', 'N/A')} | {data.get('crux', {}).get('fid_rating', 'N/A').upper()} | < 100ms |
| **CLS** | {data.get('crux', {}).get('cls', 'N/A')} | {data.get('crux', {}).get('cls_rating', 'N/A').upper()} | < 0.1 |

> Source: `{data.get('crux', {}).get('source', 'heuristic')}` — {data.get('crux', {}).get('note', 'Estimated metrics')}

---

## Suggested Topics (heuristic — not live Page-2 ranks)
*These are topic opportunities inferred from page copy, not verified SERP positions:*
"""
    striking = data.get("striking_distance_keywords", [])
    if striking:
        md += "\n| Keyword | Est. Position | Action |\n|---|---|---|\n"
        for kw in striking:
            md += f"| **{kw.get('keyword')}** | #{kw.get('estimated_position')} | {kw.get('opportunity')} |\n"
    else:
        md += "\n*No topic suggestions generated for this seed.*"

    md += f"""

---

## Identified Opportunities & Technical Issues ({len(data.get('issues', []))})
"""
    for iss in data.get("issues", []):
        md += f"- **[{iss.get('severity', 'INFO').upper()}]** {iss.get('description')}\n  *Fix:* {iss.get('recommendation')}\n"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"✓ Markdown report saved to: {filepath}")


def export_visibility_markdown(data: Dict[str, Any], filepath: str) -> None:
    md = f"""# OpenSEO-Lite AI Visibility Report
**Brand:** {data.get('brand', 'N/A')}  
**Domain:** {data.get('domain', 'N/A')}  
**Visibility Score:** {data.get('visibility_score', 0)}/100  
**Mode:** {data.get('mode', 'N/A')}  

---

## Summary
{data.get('ai_summary', 'No summary available.')}

---

## Per-query evidence
| Query | Engine | Mentioned | Cited | Status |
|---|---|---|---|---|
"""
    for row in data.get("results", []):
        md += (
            f"| {row.get('query')} | {row.get('engine')} | "
            f"{'yes' if row.get('mentioned') else 'no'} | "
            f"{row.get('cited_url') or '—'} | {row.get('status')} |\n"
        )

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"✓ Markdown report saved to: {filepath}")


def main():
    parser = argparse.ArgumentParser(description="OpenSEO-Lite CLI: Autonomous SEO Agent Toolkit")
    subparsers = parser.add_subparsers(dest="command", required=True)

    audit_parser = subparsers.add_parser("site_audit", help="Full site audit with score, issues, estimated CWV, suggested topics")
    audit_parser.add_argument("--url", required=True, help="Webpage URL to audit")
    audit_parser.add_argument("--export", choices=["json", "md"], help="Export output format (json or md)")
    audit_parser.add_argument("--output", help="Optional output filename path")

    serp_parser = subparsers.add_parser("serp_search", help="Check Google rankings for keyword")
    serp_parser.add_argument("--keyword", required=True, help="Keyword query to search")
    serp_parser.add_argument("--location", default="us", help="Two-letter country code (default: us)")
    serp_parser.add_argument("--export", choices=["json", "md"], help="Export format")
    serp_parser.add_argument("--output", help="Optional output filename path")

    page_parser = subparsers.add_parser("page_audit", help="Inspect on-page HTML factors")
    page_parser.add_argument("--url", required=True, help="Webpage URL to inspect")
    page_parser.add_argument("--export", choices=["json", "md"], help="Export format")
    page_parser.add_argument("--output", help="Optional output filename path")

    vis_parser = subparsers.add_parser("ai_visibility_check", help="Brand AI/SERP visibility score")
    vis_parser.add_argument("--brand", required=True, help="Brand or product name")
    vis_parser.add_argument("--domain", required=True, help="Primary domain (example.com)")
    vis_parser.add_argument("--live", action="store_true", help="Probe live Google SERP (default: demo fixtures)")
    vis_parser.add_argument("--export", choices=["json", "md"], help="Export format")
    vis_parser.add_argument("--output", help="Optional output filename path")

    args = parser.parse_args()

    if args.command == "site_audit":
        print(f"Running site_audit for: {args.url} ...")
        res = asyncio.run(site_audit(args.url))

        if args.export == "json":
            export_json(res, args.output or "audit_report.json")
        elif args.export == "md":
            export_markdown_report(res, args.output or "audit_report.md")
        else:
            print("\n==========================================")
            print(f"OpenSEO-Lite Score: {res['seo_score']}/100")
            print("==========================================")
            print(res.get("ai_summary", ""))
            print(f"\nIssues Found: {len(res.get('issues', []))}")
            for iss in res.get("issues", [])[:5]:
                print(f"- [{iss['severity'].upper()}] {iss['description']}")

    elif args.command == "serp_search":
        print(f"Searching Google for: '{args.keyword}' (location: {args.location}) ...")
        res = asyncio.run(serp_search(args.keyword, location=args.location))
        if args.export == "json":
            export_json(res, args.output or "serp_report.json")
        elif args.export == "md":
            lines = [f"# SERP: {res.get('keyword')}", f"Status: {res.get('status')} · Source: {res.get('source')}", ""]
            for item in res.get("results", []):
                lines.append(f"- **#{item['position']}** [{item['title']}]({item['url']})")
            path = args.output or "serp_report.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")
            print(f"✓ Markdown report saved to: {path}")
        else:
            print(f"\nTop results for '{res['keyword']}' [{res.get('status')}/{res.get('source')}]:")
            for item in res.get("results", [])[:5]:
                print(f"#{item['position']}: {item['title']} - {item['url']}")

    elif args.command == "page_audit":
        print(f"Inspecting page: {args.url} ...")
        res = asyncio.run(page_audit(args.url))
        if args.export == "json":
            export_json(res, args.output or "page_audit.json")
        elif args.export == "md":
            path = args.output or "page_audit.md"
            with open(path, "w", encoding="utf-8") as f:
                f.write(
                    f"# Page Audit: {res.get('url')}\n\n"
                    f"**Title:** {res.get('title')}\n\n"
                    f"**Words:** {res.get('word_count')}\n\n"
                    f"## Issues\n"
                    + "\n".join(f"- {i}" for i in res.get("issues", []))
                    + "\n"
                )
            print(f"✓ Markdown report saved to: {path}")
        else:
            print(json.dumps(res, indent=2))

    elif args.command == "ai_visibility_check":
        mode = "live" if args.live else "demo"
        print(f"Running ai_visibility_check for {args.brand} / {args.domain} ({mode}) ...")
        res = asyncio.run(ai_visibility_check(args.brand, args.domain, live=args.live))
        if args.export == "json":
            export_json(res, args.output or "ai_visibility.json")
        elif args.export == "md":
            export_visibility_markdown(res, args.output or "ai_visibility.md")
        else:
            print("\n==========================================")
            print(f"AI Visibility: {res['visibility_score']}/100 ({res.get('mode')})")
            print("==========================================")
            print(res.get("ai_summary", ""))


if __name__ == "__main__":
    main()
